nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        forced_allow_origin_value: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age:  42600
    paths:
        '^/': null
